version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"